"""empty message

Revision ID: 4a98e8229206
Revises: d020f18cbe78
Create Date: 2022-03-01 12:04:40.781885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a98e8229206'
down_revision = 'd020f18cbe78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'email')
    # ### end Alembic commands ###
